### ISSUE TITLE
Fatal error trying to visit site

### ISSUE THREAD

**Issue by BerkliumBirb** [symbl-cc/symbl-data#207]
Occurred trying to visit https://symbl.cc/en/1F30F/

Crash log:
```txt
Fatal error: Uncaught LogicException: unlink(/app/local/cache/data/properties/symbols/1FXXX/1F3XX/json.txt): No such file or directory (libs/Services/Cache/JsonFileCacheHandler.php, line 53) in /app/libs/Startup.php:66 Stack trace: #0 [internal function]: Startup->errorHandler(2, 'unlink(/app/loc...', 'libs/Services/C...', 53, Array) #1 /app/libs/Services/Cache/JsonFileCacheHandler.php(53): unlink('/app/local/cach...') #2 /app/libs/Services/Cache/CacheManager.php(27): Symbl\Services\Cache\JsonFileCacheHandler->forget('data.properties...') #3 /app/libs/Services/DataFileManager/DataManagers/AbstractDataManager.php(45): Symbl\Services\Cache\CacheManager->get('data.properties...') #4 /app/libs/Services/DataFileManager/DataManagers/PropertiesDataManager.php(10): Symbl\Services\DataFileManager\DataManagers\AbstractDataManager->getDataPathParsedJson('/properties/sym...') #5 /app/libs/UT/Models/emoji/Emoji.php(130): Symbl\Services\DataFileManager\DataManagers\PropertiesDataManager->getValues('symbols', '1F30F') #6 /app/libs/UT/Mo in /app/vendor/twig/twig/lib/Twig/Template.php on line 294
```

**Comment by asanov** [comment]
Fixed
